name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas (sintaxe corrigida)
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:  # Adicione estas permissões
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: feos96
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif  # Opcional: gif animado

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3  # Versão atualizada
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          force_orphan: false
