name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    # === SEÇÃO DE PERMISSÕES (ADICIONE AQUI) ===
    permissions:
      contents: write  # Permite escrever no repositório
      pages: write     # Necessário para ghaction-github-pages
      id-token: write  # Para autenticação

    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: feos96
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
